version: "3"
 
services:
  mysql-container:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=libreria
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
   
  apache-container:
    image: php:7-apache
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./miweb/:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    links: 
      - mysql-container

  phpmyadmin-container:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - mysql-container:db
